from graphene import Int, String, Boolean, relay
from graphene_sqlalchemy import SQLAlchemyObjectType
from models import ProductClass as ProductClassModel


class ProductClassAttribute():
    class_id = Int(description="Product class unique id number")
    type_id = Int(description="Product type Relationship id number")
    class_name = String(description="Name of the class")
    display_name = String(description="Name displayed of the class")
    is_system = Boolean(description="Generated by the system")


class ProductClass(SQLAlchemyObjectType, ProductClassAttribute):
    """Product Class node"""

    class Meta:
        model = ProductClassModel
        interfaces = (relay.Node,)
